### ISSUE TITLE
{Feature] Would you add the ability to copy blocks to another block code node and inside the same block code node?

### ISSUE THREAD

**Issue by 111ukasz111** [endlessm/godot-block-coding#311] opened 2024-11-06 09:08 UTC
### What Happened

I don't need to explain it.

### How to Reproduce

I don't need to explain it.

### Block Coding Plugin Version

0.7.1

### Godot Engine Version

4.3

### Operating System

Windows10

**Comment by manuq** [comment] 2024-11-06 10:36
Duplicate of #201

**Closed by manuq** 2024-11-06 10:36 UTC
